production:
  adapter: postgresql
  encoding: utf8
  database: gs_prod
  username: admin
  password: 123123
  port: 5423

development:
  adapter: postgresql
  encoding: utf8
  database: gs_dev
  host: localhost
  username: admin
  password: 123123
  port: 5423

test: &test
  adapter: postgresql
  encoding: utf8
  database: gs_test
  host: localhost
  username: admin
  password: 123123
  port: 5423

cucumber:
  <<: *test